export const LOADING_STATE_SEND = 'LOADING_STATE_SEND';
export const BOOK_DATA_SEND = 'BOOK_DATA_SEND';
export const CHOSEN_BOOK_SEND = 'CHOSEN_BOOK_SEND';
export const HIGHLIGHTS_SEND = 'HIGHLIGHTS_SEND';
export const USER_PROFILE_SEND = 'USER_PROFILE_SEND';
export const USER_MEMOS_SEND = 'USER_MEMOS_SEND';
export const USER_BOOKS_SEND = 'USER_BOOKS_SEND';
